12:24:45.735 | [36mINFO[0m    | Task run 'train_task-213' - Embedding data using scGPT...
scGPT - INFO - match 21003/27289 genes in vocabulary of size 60697.
/workspace/venvc/lib/python3.10/site-packages/scgpt/model/model.py:77: UserWarning: flash-attn is not installed, using pytorch transformer instead. Set use_fast_transformer=False to avoid this warning. Installing flash-attn is highly recommended.
  warnings.warn(
Embedding cells: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 217/217 [06:17<00:00,  1.74s/it]
/workspace/venvc/lib/python3.10/site-packages/anndata/_core/anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(
12:34:39.457 | [36mINFO[0m    | Task run 'train_task-213' - Finished in state [32mCompleted[0m()
12:34:39.459 | [31mERROR[0m   | Flow run[35m 'tiny-camel'[0m - Encountered exception during execution: AttributeError("'AnnData' object has no attribute 'result'")
Traceback (most recent call last):
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 763, in run_context
    yield self
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 1370, in run_flow_sync
    engine.call_flow_fn()
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 783, in call_flow_fn
    result = call_with_parameters(self.flow.fn, self.parameters)
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/utilities/callables.py", line 210, in call_with_parameters
    return fn(*args, **kwargs)
  File "/workspace/scGPT-niche-repo/crohn_wandb.py", line 143, in main_flow
    ref_embed_adata = train_task(dataset_path, model_path, batch_size).result()
AttributeError: 'AnnData' object has no attribute 'result'
12:34:40.282 | [36mINFO[0m    | Flow run[35m 'tiny-camel'[0m - Finished in state [31mFailed[0m("Flow run encountered an exception: AttributeError: 'AnnData' object has no attribute 'result'")
Traceback (most recent call last):
  File "/workspace/scGPT-niche-repo/crohn_wandb.py", line 163, in <module>
    main_flow(
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flows.py", line 1671, in __call__
    return run_flow(
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 1527, in run_flow
    ret_val = run_flow_sync(**kwargs)
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 1372, in run_flow_sync
    return engine.state if return_type == "state" else engine.result()
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 350, in result
    raise self._raised
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 763, in run_context
    yield self
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 1370, in run_flow_sync
    engine.call_flow_fn()
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 783, in call_flow_fn
    result = call_with_parameters(self.flow.fn, self.parameters)
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/utilities/callables.py", line 210, in call_with_parameters
    return fn(*args, **kwargs)
  File "/workspace/scGPT-niche-repo/crohn_wandb.py", line 143, in main_flow
    ref_embed_adata = train_task(dataset_path, model_path, batch_size).result()
AttributeError: 'AnnData' object has no attribute 'result'
Traceback (most recent call last):
  File "/workspace/scGPT-niche-repo/crohn_wandb.py", line 163, in <module>
    main_flow(
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flows.py", line 1671, in __call__
    return run_flow(
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 1527, in run_flow
    ret_val = run_flow_sync(**kwargs)
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 1372, in run_flow_sync
    return engine.state if return_type == "state" else engine.result()
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 350, in result
    raise self._raised
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 763, in run_context
    yield self
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 1370, in run_flow_sync
    engine.call_flow_fn()
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 783, in call_flow_fn
    result = call_with_parameters(self.flow.fn, self.parameters)
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/utilities/callables.py", line 210, in call_with_parameters
    return fn(*args, **kwargs)
  File "/workspace/scGPT-niche-repo/crohn_wandb.py", line 143, in main_flow
    ref_embed_adata = train_task(dataset_path, model_path, batch_size).result()
AttributeError: 'AnnData' object has no attribute 'result'
