12:12:39.102 | [36mINFO[0m    | Task run 'train_task-fb6' - Embedding data using scGPT...
12:12:39.116 | [31mERROR[0m   | Task run 'train_task-fb6' - Task run failed with exception: NotADirectoryError(20, 'Not a directory') - Retries are exhausted
Traceback (most recent call last):
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/task_engine.py", line 813, in run_context
    yield self
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/task_engine.py", line 1389, in run_task_sync
    engine.call_task_fn(txn)
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/task_engine.py", line 830, in call_task_fn
    result = call_with_parameters(self.task.fn, parameters)
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/utilities/callables.py", line 210, in call_with_parameters
    return fn(*args, **kwargs)
  File "/workspace/scGPT-niche-repo/crohn_wandb.py", line 53, in train_task
    ref_embed_adata = scg.tasks.embed_data(
  File "/workspace/venvc/lib/python3.10/site-packages/scgpt/tasks/cell_emb.py", line 208, in embed_data
    vocab = GeneVocab.from_file(vocab_file)
  File "/workspace/venvc/lib/python3.10/site-packages/scgpt/tokenizer/gene_tokenizer.py", line 78, in from_file
    with file_path.open("r") as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
NotADirectoryError: [Errno 20] Not a directory: 'models/best_model.pt/vocab.json'
12:12:39.152 | [31mERROR[0m   | Task run 'train_task-fb6' - Finished in state [31mFailed[0m("Task run encountered an exception NotADirectoryError: [Errno 20] Not a directory: 'models/best_model.pt/vocab.json'")
12:12:39.153 | [31mERROR[0m   | Flow run[35m 'eager-weasel'[0m - Encountered exception during execution: NotADirectoryError(20, 'Not a directory')
Traceback (most recent call last):
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 763, in run_context
    yield self
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 1370, in run_flow_sync
    engine.call_flow_fn()
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 783, in call_flow_fn
    result = call_with_parameters(self.flow.fn, self.parameters)
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/utilities/callables.py", line 210, in call_with_parameters
    return fn(*args, **kwargs)
  File "/workspace/scGPT-niche-repo/crohn_wandb.py", line 143, in main_flow
    ref_embed_adata = train_task(dataset_path, model_path, batch_size).result()
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/tasks.py", line 1063, in __call__
    return run_task(
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/task_engine.py", line 1604, in run_task
    return run_task_sync(**kwargs)
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/task_engine.py", line 1391, in run_task_sync
    return engine.state if return_type == "state" else engine.result()
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/task_engine.py", line 484, in result
    raise self._raised
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/task_engine.py", line 813, in run_context
    yield self
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/task_engine.py", line 1389, in run_task_sync
    engine.call_task_fn(txn)
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/task_engine.py", line 830, in call_task_fn
    result = call_with_parameters(self.task.fn, parameters)
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/utilities/callables.py", line 210, in call_with_parameters
    return fn(*args, **kwargs)
  File "/workspace/scGPT-niche-repo/crohn_wandb.py", line 53, in train_task
    ref_embed_adata = scg.tasks.embed_data(
  File "/workspace/venvc/lib/python3.10/site-packages/scgpt/tasks/cell_emb.py", line 208, in embed_data
    vocab = GeneVocab.from_file(vocab_file)
  File "/workspace/venvc/lib/python3.10/site-packages/scgpt/tokenizer/gene_tokenizer.py", line 78, in from_file
    with file_path.open("r") as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
NotADirectoryError: [Errno 20] Not a directory: 'models/best_model.pt/vocab.json'
12:12:39.500 | [36mINFO[0m    | Flow run[35m 'eager-weasel'[0m - Finished in state [31mFailed[0m("Flow run encountered an exception: NotADirectoryError: [Errno 20] Not a directory: 'models/best_model.pt/vocab.json'")
Traceback (most recent call last):
  File "/workspace/scGPT-niche-repo/crohn_wandb.py", line 163, in <module>
    main_flow(
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flows.py", line 1671, in __call__
    return run_flow(
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 1527, in run_flow
    ret_val = run_flow_sync(**kwargs)
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 1372, in run_flow_sync
    return engine.state if return_type == "state" else engine.result()
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 350, in result
    raise self._raised
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 763, in run_context
    yield self
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 1370, in run_flow_sync
    engine.call_flow_fn()
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 783, in call_flow_fn
    result = call_with_parameters(self.flow.fn, self.parameters)
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/utilities/callables.py", line 210, in call_with_parameters
    return fn(*args, **kwargs)
  File "/workspace/scGPT-niche-repo/crohn_wandb.py", line 143, in main_flow
    ref_embed_adata = train_task(dataset_path, model_path, batch_size).result()
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/tasks.py", line 1063, in __call__
    return run_task(
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/task_engine.py", line 1604, in run_task
    return run_task_sync(**kwargs)
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/task_engine.py", line 1391, in run_task_sync
    return engine.state if return_type == "state" else engine.result()
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/task_engine.py", line 484, in result
    raise self._raised
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/task_engine.py", line 813, in run_context
    yield self
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/task_engine.py", line 1389, in run_task_sync
    engine.call_task_fn(txn)
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/task_engine.py", line 830, in call_task_fn
    result = call_with_parameters(self.task.fn, parameters)
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/utilities/callables.py", line 210, in call_with_parameters
    return fn(*args, **kwargs)
  File "/workspace/scGPT-niche-repo/crohn_wandb.py", line 53, in train_task
    ref_embed_adata = scg.tasks.embed_data(
  File "/workspace/venvc/lib/python3.10/site-packages/scgpt/tasks/cell_emb.py", line 208, in embed_data
    vocab = GeneVocab.from_file(vocab_file)
  File "/workspace/venvc/lib/python3.10/site-packages/scgpt/tokenizer/gene_tokenizer.py", line 78, in from_file
    with file_path.open("r") as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
NotADirectoryError: [Errno 20] Not a directory: 'models/best_model.pt/vocab.json'
Traceback (most recent call last):
  File "/workspace/scGPT-niche-repo/crohn_wandb.py", line 163, in <module>
    main_flow(
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flows.py", line 1671, in __call__
    return run_flow(
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 1527, in run_flow
    ret_val = run_flow_sync(**kwargs)
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 1372, in run_flow_sync
    return engine.state if return_type == "state" else engine.result()
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 350, in result
    raise self._raised
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 763, in run_context
    yield self
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 1370, in run_flow_sync
    engine.call_flow_fn()
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/flow_engine.py", line 783, in call_flow_fn
    result = call_with_parameters(self.flow.fn, self.parameters)
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/utilities/callables.py", line 210, in call_with_parameters
    return fn(*args, **kwargs)
  File "/workspace/scGPT-niche-repo/crohn_wandb.py", line 143, in main_flow
    ref_embed_adata = train_task(dataset_path, model_path, batch_size).result()
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/tasks.py", line 1063, in __call__
    return run_task(
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/task_engine.py", line 1604, in run_task
    return run_task_sync(**kwargs)
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/task_engine.py", line 1391, in run_task_sync
    return engine.state if return_type == "state" else engine.result()
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/task_engine.py", line 484, in result
    raise self._raised
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/task_engine.py", line 813, in run_context
    yield self
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/task_engine.py", line 1389, in run_task_sync
    engine.call_task_fn(txn)
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/task_engine.py", line 830, in call_task_fn
    result = call_with_parameters(self.task.fn, parameters)
  File "/workspace/venvc/lib/python3.10/site-packages/prefect/utilities/callables.py", line 210, in call_with_parameters
    return fn(*args, **kwargs)
  File "/workspace/scGPT-niche-repo/crohn_wandb.py", line 53, in train_task
    ref_embed_adata = scg.tasks.embed_data(
  File "/workspace/venvc/lib/python3.10/site-packages/scgpt/tasks/cell_emb.py", line 208, in embed_data
    vocab = GeneVocab.from_file(vocab_file)
  File "/workspace/venvc/lib/python3.10/site-packages/scgpt/tokenizer/gene_tokenizer.py", line 78, in from_file
    with file_path.open("r") as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
NotADirectoryError: [Errno 20] Not a directory: 'models/best_model.pt/vocab.json'
